[workspace]
resolver = "2"
members = ["ndl", "ndld", "ndl-core"]

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["hi@pgray.dev"]
license = "MIT"
repository = "https://github.com/pgray/ndl"
